### ISSUE TITLE
Issues with bypass set to true when working locally

### ISSUE THREAD

**Issue by olimorris** [Vinelab/cdn#40]
When 'bypass' is set to true I notice that visiting pages deep within my website, do not display the assets. For example, visiting ```http://myapp.dev/``` will load assets fine. However if I visit ```http://myapp.dev/messages/show/15``` then as the asset is not absolute, they don't display.

Looking at how Laravel's ```Url::asset()``` feature works it appears that an absolute url is always generated to the assets. However in your CdnFacade.php file, only the ```$path``` is returned.

**Comment by RajeshHegde** [comment]
Is this issue is fixed in the latest version.?

**Comment by Mahmoudz** [comment]
@RajeshHegde it should be fixed by the latest release.
