### ISSUE TITLE
Exception on using cloudfront

### ISSUE THREAD

**Issue by hiddenl00p** [Vinelab/cdn#56]
I am getting below exception on trying to configure cloudfront. 

'cloudfront' => [
                    'use'       => true,
                    'cdn_url'   => 'XYZ.cloudfront.net',
                    'version'   => '',
                ],

ErrorException in AwsS3Provider.php line 258:
Undefined index: scheme (View: /home/vagrant/code/xyz-dev/resources/views/layouts/application.blade.php) (View: /home/vagrant/code/xyz-dev/resources/views/layouts/application.blade.php)

**Comment by olimorris** [comment]
That seems odd. Can you show me what's on line 258. Also, my Cloudfront URL is entered with ```https://```. Try that.

**Comment by hiddenl00p** [comment]
Thanks that worked for me. I forgot to update here.

**Comment by olimorris** [comment]
Can we close this down please @Mulkave
