### ISSUE TITLE
[Aws\S3\Exception\PermanentRedirectException]

### ISSUE THREAD

**Issue by CodyLee117** [Vinelab/cdn#63]
I'm getting this exceptions when trying a cdn:push.

  [Aws\S3\Exception\PermanentRedirectException]
  The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint: "my.bucket.name.s3.amazonaws.com".

It seems like it might be because my bucket name has a period in it because I didn't have any issues until I renamed the bucket.

I was able to fix this by changing my CDN url to 'http://s3.amazonaws.com/'
and adding 'region' => 'my-region' to client instantiation in AwsS3Provider, so it looks like this:

S3Client::factory(array(
    'key'    => $this->credential_key,
    'secret' => $this->credential_secret,
    'region' => 'us-west-2'
  )
)

It appears that a region setting might be in order for the cdn configuration.

**Comment by olimorris** [comment]
This will also be fixed in #72
