### ISSUE TITLE
Laravel 5.1 Support

### ISSUE THREAD

**Issue by azcoppen** [Vinelab/cdn#66]
Installation fails with Laravel 5.1, as "illuminate/support": "5.0.*" dependency needs to be 5.1.

**Comment by olimorris** [comment]
Hi - I've submitted a pull request (#65) and just waiting for the guys to merge and tag.

**Comment by azcoppen** [comment]
@olimorris Nice job. Only problem left i can see is the AWS issue you mentioned. File Storage requires v3, whereas the dependency is still at ~2.x. Going to be fun getting around that one.

**Comment by olimorris** [comment]
We should still be okay: http://laravel.com/docs/5.1/upgrade#upgrade-5.1.0

It looks like AWS v3.0 is only need for people who use the AWS Queue or Email driver. Admittedly this does need to get built into the package at sometime.

**Comment by azcoppen** [comment]
I'm unfortunately getting this now when specifying v3 as per 5.1 storage spec: "CDN provider (aws.s3) is not supported"

**Comment by olimorris** [comment]
I don't think the guys have tagged my patch yet so I can't recreate this. I'll see what the change in AWS v3 is and work on a fix

**Comment by Mulkave** [comment]
Sorry, tagged as [v1.1.6](https://github.com/Vinelab/cdn/releases/tag/v1.1.6) now. @azcoppen please try again and let us know.
