### ISSUE TITLE
Laravel 5.1 functions require AWS v3 & Guzzle v5

### ISSUE THREAD

**Issue by azcoppen** [Vinelab/cdn#67]
As per upgrade info: http://laravel.com/docs/5.1/upgrade

"If you are using the AWS SQS queue driver or the AWS SES e-mail driver, you should update your installed AWS PHP SDK to version 3.0. If you are using the Amazon S3 filesystem driver, you will need to update the corresponding Flysystem package via Composer: Amazon S3: league/flysystem-aws-s3-v3 ~1.0"

Guzzle 5 is required for mail, etc.

Installing vinelab/cdn now gives:

Problem 1
    - Installation request for aws/aws-sdk-php 3.* -> satisfiable by aws/aws-sdk-php[3.0.0, 3.0.0-beta.1, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.x-dev].
    - vinelab/cdn v1.1.1 requires aws/aws-sdk-php 2.7.* -> no matching package found.
    - vinelab/cdn v1.1.0 requires aws/aws-sdk-php 2.7.* -> no matching package found.
    - vinelab/cdn v1.0.1 requires aws/aws-sdk-php 2.7.* -> no matching package found.
    - vinelab/cdn v1.0.0-beta.3 requires guzzlehttp/guzzle ~4.0 -> no matching package found.
    - vinelab/cdn v1.0.0-beta.2 requires guzzlehttp/guzzle ~4.0 -> no matching package found.
    - vinelab/cdn v1.0.0-beta.1 requires guzzlehttp/guzzle ~4.0 -> no matching package found.
    - vinelab/cdn v1.0.0 requires guzzlehttp/guzzle ~4.0 -> no matching package found.
    - vinelab/cdn dev-master requires aws/aws-sdk-php 2.8.* -> satisfiable by aws/aws-sdk-php[2.8.x-dev].
    - vinelab/cdn v1.1.2 requires aws/aws-sdk-php 2.8.* -> satisfiable by aws/aws-sdk-php[2.8.x-dev].
    - vinelab/cdn v1.1.3 requires aws/aws-sdk-php 2.8.* -> satisfiable by aws/aws-sdk-php[2.8.x-dev].
    - vinelab/cdn v1.1.4 requires aws/aws-sdk-php 2.8.* -> satisfiable by aws/aws-sdk-php[2.8.x-dev].
    - vinelab/cdn v1.1.5 requires aws/aws-sdk-php 2.8.* -> satisfiable by aws/aws-sdk-php[2.8.x-dev].
    - Conclusion: don't install aws/aws-sdk-php 2.8.x-dev
    - Installation request for vinelab/cdn * -> satisfiable by vinelab/cdn[dev-master, v1.0.0, v1.0.0-beta.1, v1.0.0-beta.2, v1.0.0-beta.3, v1.0.1, v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5].

**Comment by olimorris** [comment]
I had no issues with v1.1.6. Have you tried installing that?

**Comment by azcoppen** [comment]
Using "vinelab/cdn": "*" in composer as suggested, which should load 1.1.16: https://packagist.org/packages/vinelab/cdn

**Comment by olimorris** [comment]
I've made another pull request to include updated Guzzle and AWS drivers which will form v1.1.17

**Comment by Mulkave** [comment]
resolved in #69 thanks @olimorris
