### ISSUE TITLE
dependency guzzlehttp  version conflict 

### ISSUE THREAD

**Issue by MezaTech** [Vinelab/cdn#68]
could you update composer.json to use version  6.*  ? , cause some of other package dependencies  

    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.0.1, 5.3.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.0.x-dev, 5.3.x-dev].
    - vinelab/cdn dev-master requires guzzlehttp/guzzle ~5.3 -> satisfiable by guzzlehttp/guzzle[5.3.x-dev].
    - Installation request for vinelab/cdn dev-master -> satisfiable by vinelab/cdn[dev-master].
    - Installation request for guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.x-dev].

**Comment by olimorris** [comment]
I've just done a pull request for this.

**Comment by Mulkave** [comment]
resolved in #69 thanks @olimorris

**Comment by olimorris** [comment]
Can we tag the #69 in v1.1.7 as it resolves all issues but we need to tell people to use v3 of Flysystem AWS-S3 as opposed to v2
