### ISSUE TITLE
Region and Version  required

### ISSUE THREAD

**Issue by MezaTech** [Vinelab/cdn#71]
could you add Region and version to connect function and check compatibility with Guzzle 

Config example : 
  // Instantiate an S3 client
            $this->setS3Client(
                new S3Client(array(
                        'key'     => $this->credential_key,
                        'secret'  => $this->credential_secret,
                        'region'  => $this->region,
                        'version' => $this->version
                    )
                )
            );

**Comment by olimorris** [comment]
I've fixed this in #72 but the tests need addressing before it can be merged.
