### ISSUE TITLE
Add different  metadata to each directory 

### ISSUE THREAD

**Issue by MezaTech** [Vinelab/cdn#75]
current version has ability to add  Add metadata to all files in directories which added to " include " array .

but some time we need to different meta to selected files ,

example : add "ContentEncoding =>  gzip " to Styles and JS

**Comment by Mahmoudz** [comment]
@olimorris since you added the support for `metadata`.. Can you please answer this.
Thanks.

**Comment by olimorris** [comment]
Valid question. This can be added into the metadata array as 'Content-Encoding' => 'gzip' but it cannot yet do it for different types of files. Something to work on for v1.2.1.

@MezaTech - is there a reason why you wouldn't just gzip everything?!

**Comment by olimorris** [comment]
@MezaTech is this still an issue?

**Comment by olimorris** [comment]
@Mahmoudz - I think we can close this.

**Comment by chriscarter37** [comment]
I cannot get any gzip to work.  Here is my code in the cdn.php config file.

`'metadata' => [
                    'Content-Encoding' => 'gzip'
                ],`

Any idea as to why this isn't working?

**Comment by Mulkave** [comment]
@chriscarter37 can you please elaborate on the error you're getting? (if any)
