### ISSUE TITLE
Laravel 4 support

### ISSUE THREAD

**Issue by tvillafane** [Vinelab/cdn#76]
This looks like a great tool!  I stumbled across it on multiple forums as I was configuring my S3 bucket with Laravel and CloudFront.  I am wondering about your wording in the description of the project; when you say that the project "supports Laravel 5.1".  Does this mean that the current version doesn NOT support Laravel 4.2?  If so, should I use the 1.0.1 release?

**Comment by Mahmoudz** [comment]
@tvillafane the package is really amazing.
I think `v1.0.1` was the last release supporting laravel 4.2
Can you try it and let us know if it works? In order to add it in the documentation and rename that release.
Thank you for your question.

**Comment by tvillafane** [comment]
@Mahmoudz the package is beautiful.  It installed quite easily with Laravel 4.2 and the configuration is simple.  Very powerful piece of software.

I thank you very much for making it so easy to use.  I personally love the ability to push to S3 with a terminal command because it ensures I know exactly when the CDN will be updated and so forth.  Great work on this.

**Comment by Mahmoudz** [comment]
@tvillafane we are glade you enjoy it, thank you for your wonderful feedback.
