### ISSUE TITLE
Exception while uploading "Too many files open"

### ISSUE THREAD

**Issue by Yavor-Ivanov** [Vinelab/cdn#79]
I've added my Laravel public folder to be uploaded to an S3 bucket, but get this exception some time into the upload when running ```./artisan cdn:push```:
```[ErrorException]                                                                                                                     
  fopen(/var/www/labworm/public/packages/frozennode/administrator/img/ico/apple-touch-icon-144-precomposed.png): failed to open strea  
  m: Too many open files
```

It seems like the file handles are never released when uploading.

**Comment by Mulkave** [comment]
If I'm not mistaken, this usually has to do with the allowed files by `php.ini`. Can you please try updating that?

**Comment by olimorris** [comment]
Yes this is not an error I've come across with the AWS PHP SDK.

**Comment by Mulkave** [comment]
@Yavor-Ivanov any update on this issue? Seems like it's an AWS PHP SDK issue as @olimorris mentioned.

**Comment by Yavor-Ivanov** [comment]
(#79)
In-Reply-To: <Vinelab/cdn/issues/79/129374267@github.com> 

I've tried using the Amazon SDK directly and get the same results when 
uploading a folder a lot of files in it. I've since switched to calling the 
s3cmd tool.

**Comment by Mulkave** [comment]
@Yavor-Ivanov alright, thanks for the feedback. Closing since it is not a CDN issue.
