### ISSUE TITLE
noob help with loading url

### ISSUE THREAD

**Issue by og6k** [Vinelab/cdn#81]
I installed and upload without a problem. When I call the url with
    link rel="stylesheet" href="{{ Cdn::asset('/path/to/css/all.css') }}" 
The url is not being loaded. Instead it prints out the exact cdn::asset() in frontend. How can I fix this?

**Comment by Mulkave** [comment]
This is probably due to the `bypass` in your configuration https://github.com/Vinelab/cdn#bypass

**Comment by olimorris** [comment]
Have you registered the Facade?

**Comment by og6k** [comment]
I just gave up on trying and put the url manually
