### ISSUE TITLE
Laravel 5.2 Support?

### ISSUE THREAD

**Issue by azcoppen** [Vinelab/cdn#86]
Latest release requires Symfony Console 2.7, but L5.2 needs 2.8 or 3.0  

    - Conclusion: don't install symfony/console v3.0.0
    - Installation request for vinelab/cdn * -> satisfiable by vinelab/cdn[v1.0.0, v1.0.1, v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7, v1.1.8, v1.2.0].
    - Conclusion: don't install laravel/framework v5.2.3
    - laravel/framework v5.2.0 requires symfony/console 2.8.*|3.0.* -> satisfiable by symfony/console[v2.8.0, v3.0.0].
    - laravel/framework v5.2.1 requires symfony/console 2.8.*|3.0.* -> satisfiable by symfony/console[v2.8.0, v3.0.0].
    - laravel/framework v5.2.2 requires symfony/console 2.8.*|3.0.* -> satisfiable by symfony/console[v2.8.0, v3.0.0].
    - Conclusion: don't install symfony/console v2.8.0
    - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[v5.2.0, v5.2.1, v5.2.2, v5.2.3].

**Comment by paulocastellano** [comment]
+1

**Comment by publiux** [comment]
I've created pull request #91 to address this issue.

**Comment by publiux** [comment]
I have created a fork that supports Laravel 5.2 and will be actively maintained. https://github.com/publiux/laravelcdn

**Comment by paulocastellano** [comment]
Thanks bro!

I will test it now, if u need any for dev/update tell me!

Bye
-- 
Atenciosamente,
Paulo Castellano
Software Engineer
+55 (13) 99186-1554

**Comment by hiddenl00p** [comment]
+1

**Comment by vovanmix** [comment]
+1, Need this a lot!

**Comment by azcoppen** [comment]
Is there any update on this? Can't really change packages in our app yet unfortunately.

**Comment by Mulkave** [comment]
@azcoppen Just pushed an attempt for support to master (can't really test now), please require `dev-master` in your composer and give it a shot :smile:

**Comment by azcoppen** [comment]
Thank you! Neither * or dev-master trigger any changes when running composer: old file specifies 2.7, and latest change is 2.*, presumably meaning the requirement is already satisfied?

**Comment by Mulkave** [comment]
@azcoppen thanks, seems to work for me. Released v1.4.0 which has Laravel 5.2 compatibility. Enjoy!

**Comment by azcoppen** [comment]
@Mulkave Apologies, i'm an idiot. Ran update without adding Laravel 5.2. Not enough coffee yesterday. Thanks for the update, champ.

**Comment by Mulkave** [comment]
@azcoppen haha no worries, cheers! ☕️
