### ISSUE TITLE
Undefined index: http in AwsS3Provider.php:140

### ISSUE THREAD

**Issue by crarau** [Vinelab/cdn#96]
I'm getting the error below. Is it something that I'm doing wrong? Using the latest codebase.

production.ERROR: ErrorException: Undefined index: http in /srv/wisk/wisksol/vendor/vinelab/cdn/src/Vinelab/Cdn/Providers/AwsS3Provider.php:140
Stack trace:
#0 /srv/wisk/wisksol/vendor/vinelab/cdn/src/Vinelab/Cdn/Providers/AwsS3Provider.php(140): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/srv/wisk/wisks...', 140, Array)
#1 /srv/wisk/wisksol/vendor/vinelab/cdn/src/Vinelab/Cdn/ProviderFactory.php(50): Vinelab\Cdn\Providers\AwsS3Provider->init(Array)
#2 /srv/wisk/wisksol/vendor/vinelab/cdn/src/Vinelab/Cdn/CdnFacade.php(170): Vinelab\Cdn\ProviderFactory->create(Array)
#3 /srv/wisk/wisksol/vendor/vinelab/cdn/src/Vinelab/Cdn/CdnFacade.php(64): Vinelab\Cdn\CdnFacade->init()
#4 [internal function]: Vinelab\Cdn\CdnFacade->__construct(Object(Vinelab\Cdn\ProviderFactory), Object(Vinelab\Cdn\CdnHelper), Object(Vinelab\Cdn\Validators\CdnFacadeValidator))
#5 /srv/wisk/wisksol/bootstrap/cache/compiled.php(1306): ReflectionClass->newInstanceArgs(Array)

Thanks,
Chip.

**Comment by Mulkave** [comment]
Please update to v1.4.3, attempts to solve this issue.

**Comment by azcoppen** [comment]
Getting the same, and on dev branch:

ErrorException in AwsS3Provider.php line 140:
Undefined index: http

  - Updating vinelab/cdn dev-master (c92b281 => 802dfae)
    Checking out 802dfae072795bb812ef5fa2bdd658a259cb093a
    Pulling in changes:
      802dfae - Abed Halawi: any of 2.* or 3.* for symfony components should work
      3be5c0a - Abed Halawi: fix aws s3 provider tests by adding http config param
      65b7748 - Abed Halawi: php 7 supported and failure is only allowed for hhvm
      c0094c3 - Abed Halawi: fix an issue for non-pem users

**Comment by Mulkave** [comment]
weird, the attempt to solve this was to add an `http` to the defaults as in here: https://github.com/Vinelab/cdn/blob/master/src/Vinelab/Cdn/Providers/AwsS3Provider.php#L52

which will be merged with the config later on so regardless of whether there's an `http` in the config or not it should be working: https://github.com/Vinelab/cdn/blob/master/src/Vinelab/Cdn/Providers/AwsS3Provider.php#L129

can you please check your `composer.lock` file, check for the commit of vinelab/cdn that's been installed on your side? Thanks!

**Comment by marcaube** [comment]
@Mulkave that's not quite how array_merge works with recursive arrays, e.g.

```php
$default = [
    'foo' => [
        'bar' => 1,
        'baz' => 2
    ]
];

$configurations = [
    'foo' => [
        'qux' => 3
    ]
];

array_merge($default, $configurations); // ['foo' => ['qux' => 3]]
```

First-level elements of the first array will be replaced entirely by elements of the second array.
